### ISSUE TITLE
Bug in special Character ' " '

### ISSUE THREAD

**Issue by abm6** [Meghdut-Mandal/TyperX#6]
please check on all special characters if they are working fine.
In my case ' " ' gets simulated to '~' 

![image](https://user-images.githubusercontent.com/55770187/106235829-88976c80-6221-11eb-8442-95f86d7dd009.png)

**Comment by Meghdut-Mandal** [comment]
Please use the latest version. This bug is already fixed https://github.com/Meghdut-Mandal/TyperX/raw/master/dist/TyperX.jar
